openapi: 3.1.0
info:
  title: Financial Tracking API
  version: 0.0.1

paths:
  /link-tokens/create:
    post:
      responses:
        '200':
          description: Successful Response
          application/json:
            schema:
              type: object
              properties:
                link_token:
                  type: string
                expiration:
                  type: string
                request_id:
                  type: string
        default:
          description: Error response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorSchema'
  /link-tokens/exchange:
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PostLinkTokensExchangeRequestBody'
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                type: object
                properties:
                  itemId:
                    type: string
        default:
          description: Error response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorSchema'

components:
  schemas:
    PostLinkTokensExchangeRequestBody:
      type: object
      properties:
        publicToken:
          type: string
      required:
        - publicToken
    ErrorSchema:
      type: object
      properties:
        message:
          type: string
        details:
          type: object
        trackingId:
          type: string
